---

- src: https://github.com/FlyingBinary/ansible-role-homebrew.git
  name: IanTaylorFB.superlumic-homebrew
  version: fbmaster

- src: https://github.com/FlyingBinary/ansible-role-osx-defaults.git
  name: IanTaylorFB.superlumic-osx-defaults
  version: fbmaster

- src: https://github.com/FlyingBinary/ansible-role-computername.git
  name: IanTaylorFB.superlumic-computername
  version: fbmaster

- src: https://github.com/FlyingBinary/ansible-role-google-fonts.git
  name: IanTaylorFB.superlumic-google-fonts
  version: fbmaster

- src: https://github.com/FlyingBinary/ansible-role-chrome-extensions.git
  name: IanTaylorFB.superlumic-chrome-extensions
  version: fbmaster

- src: https://github.com/FlyingBinary/ansible-role-mas.git
  name: IanTaylorFB.superlumic-mas
  version: fbmaster

- src: https://github.com/FlyingBinary/ansible-role-cli.git
  name: IanTaylorFB.superlumic-cli
  version: fbmaster

#  - src: https://github.com/FlyingBinary/ansible-role-mysql.git
#    name: IanTaylorFB.superlumic-mysql
#    version: fbmaster
#
#  - src: https://github.com/FlyingBinary/ansible-role-php.git
#    name: IanTaylorFB.superlumic-php
#    version: fbmaster
#
#  - src: https://github.com/FlyingBinary/ansible-role-sublimetext.git
#    name: IanTaylorFB.superlumic-sublimetext
#    version: fbmaster
#
#  - src: https://github.com/FlyingBinary/ansible-role-node.git
#    name: IanTaylorFB.superlumic-node
#    version: fbmaster
#
#  - src: https://github.com/FlyingBinary/ansible-role-postgresql.git
#    name: IanTaylorFB.superlumic-postgresql
#    version: fbmaster
#
#  - src: https://github.com/FlyingBinary/ansible-role-vim.git
#    name: IanTaylorFB.superlumic-vim
#    version: fbmaster
#
#  - src: https://github.com/FlyingBinary/ansible-role-modjk.git
#    name: IanTaylorFB.superlumic-modjk
#    version: fbmaster
#
#  - src: https://github.com/FlyingBinary/ansible-role-skylab.git
#    name: IanTaylorFB.superlumic-skylab
#    version: fbmaster
