---

- hosts: localhost
  connection: local

  roles:
    - profile-all
    - IanTaylorFB.superlumic-computername
    # These are getting called twice
    #    - IanTaylorFB.superlumic-osx-defaults
    #    - IanTaylorFB.superlumic-homebrew
    - IanTaylorFB.superlumic-google-fonts
    - IanTaylorFB.superlumic-chrome-extensions
    - IanTaylorFB.superlumic-mas
    - IanTaylorFB.superlumic-cli

  vars:
    - computername: trixie
    - configure_git: no
    - personal_google_fonts: []
    - personal_homebrew_packages: []

    - personal_homebrew_cask_apps:
        - bbedit

    - mas_email: "jacqui.taylor@flyingbinary.com"
    - mas_signin_dialog: yes
    - mas_installed_apps:
        - { id: 409183694, name: "Keynote (7.1.1)" }
        - { id: 409201541, name: "Pages (6.1.1)" }
        - { id: 409203825, name: "Numbers (4.2)" }
    - common_mas_apps:
        - { id: 409183694, name: "Keynote (7.1.1)" }
        - { id: 409201541, name: "Pages (6.1.1)" }
        - { id: 409203825, name: "Numbers (4.2)" }
        - { id: 441258766, name: "Magnet" }
    - unusual_mas_apps:
        - { id: 1091189122, name: "Bear" }
        - { id: 408981434, name: "iMovie (10.1)" }
    - rare_mas_apps:
        - { id: 485812721, name: "TweetDeck (3.9.889)" }
        - { id: 424389933, name: "Final Cut Pro (10.2.2)" }
        - { id: 434290957, name: "Motion (5.2.2)" }
        - { id: 408981381, name: "iPhoto (9.6.1)" }
        - { id: 682658836, name: "GarageBand (10.1.6)" }
    - use_brew_instead:
        - { id: 406056744, name: "Evernote (6.11.1)" }


    - osx_defaults:
        - domain: 'com.apple.dock'
          key: 'show-process-indicators'
          type: boolean
          value: true
        - domain: 'com.apple.screencapture'
          key: 'type'
          type: string
          value: png
        - domain: 'NSGlobalDomain'
          key: 'KeyRepeat'
          type: integer
          value: 2
        - domain: 'NSGlobalDomain'
          key: 'InitialKeyRepeat'
          type: integer
          value: 15
        - domain: 'com.apple.menuextra.battery'
          key: 'ShowPercent'
          type: string
          value: 'YES'
        - domain: 'com.apple.finder'
          key: 'FXPreferredViewStyle'
          type: string
          value: "clmv"
        - domain: 'NSGlobalDomain'
          key: 'NSNavPanelExpandedStateForSaveMode'
          type: boolean
          value: true
        - domain: 'NSGlobalDomain'
          key: 'PMPrintingExpandedStateForPrint'
          type: boolean
          value: true
        - domain: 'NSGlobalDomain'
          key: 'NSQuitAlwaysKeepsWindows'
          type: boolean
          value: false
        - domain: 'com.apple.desktopservices'
          key: 'DSDontWriteNetworkStores'
          type: boolean
          value: true
        - domain: 'com.apple.print.PrintingPrefs'
          key: 'Quit When Finished'
          type: boolean
          value: true
