---

- hosts: localhost
  connection: local

  roles:
    - profile-all
    - IanTaylorFB.superlumic-homebrew
    - IanTaylorFB.superlumic-google-fonts
    - IanTaylorFB.superlumic-chrome-extensions

  vars:
    - computername: trixie
    - configure_git: no
    - personal_google_fonts:
        - "Indie Flower"
    - personal_homebrew_packages:
        - openssl

    - personal_homebrew_cask_apps:
        - dropbox
#    - personal_homebrew_cask_apps:
#        - firefox
#        - google-chrome
#
#
#        ### Standard applications
#        - dropbox
#        - evernote
#        - firefox
#        - tableau
#        ### QuickLook plugins
#        - qlstephen
#        - quicklook-csv
#        - qlmarkdown
#        ### Security tools from https://objective-see.com/index.html
#        - blockblock
#        # - dylibhijackscanner # not found in brew cask search
#        - kextviewr
#        - knockknock
#        - lockdown # not working on Sierra 10.12
#        # - ostiarius # not needed after El Capitan 10.11
#        - oversight
#        - ransomwhere
#        - taskexplorer
#        - whatsyoursign

    - osx_defaults:
        - domain: 'com.apple.dock'
          key: 'show-process-indicators'
          type: boolean
          value: true
        - domain: 'com.apple.screencapture'
          key: 'type'
          type: string
          value: png
        - domain: 'NSGlobalDomain'
          key: 'KeyRepeat'
          type: integer
          value: 2
        - domain: 'NSGlobalDomain'
          key: 'InitialKeyRepeat'
          type: integer
          value: 15
        - domain: 'com.apple.menuextra.battery'
          key: 'ShowPercent'
          type: string
          value: 'YES'
        - domain: 'com.apple.finder'
          key: 'FXPreferredViewStyle'
          type: string
          value: "clmv"
        - domain: 'NSGlobalDomain'
          key: 'NSNavPanelExpandedStateForSaveMode'
          type: boolean
          value: true
        - domain: 'NSGlobalDomain'
          key: 'PMPrintingExpandedStateForPrint'
          type: boolean
          value: true
        - domain: 'NSGlobalDomain'
          key: 'NSQuitAlwaysKeepsWindows'
          type: boolean
          value: false
        - domain: 'com.apple.desktopservices'
          key: 'DSDontWriteNetworkStores'
          type: boolean
          value: true
        - domain: 'com.apple.print.PrintingPrefs'
          key: 'Quit When Finished'
          type: boolean
          value: true


#      # 6 The OSX application firewall is enabled (system-wide).
#      - domain: 'com.apple.alf'
#        key: 'globalstate'
#        type: boolean
#        value: true
#      # 8 A password is required to wake the computer from sleep or screen saver (system-wide)
#      - domain: 'com.apple.'
#        key: ''
#        type: boolean
#        value: true
#      com.apple.screensaver askForPassword -bool true
#      # 10 There is no delay between starting the screen saver and locking the machine (system-wide)
#      com.apple.screensaver askForPasswordDelay -bool false
#      # 12 Logging is enabled for the operating system
#      com.apple.alf loggingenabled -bool true
#      # 14 Stealth mode is enabled for OSX: Computer does not respond to ICMP ping requests or connection attempts from a closed TCP/UDP port. (system-wide)
#      com.apple.alf stealthenabled -bool true"
#      # 16 Automatic whitelisting of Apple-signed applications through the firewall is disabled (system-wide)
#      com.apple.alf allowsignedenabled -bool false
#      # 18 Captive portal for connecting to new networks is disabled to prevent MITM attacks
#      com.apple.captive.control Active -bool false
#      # 20 Hidden files are displayed in Finder
#      # TODO: Requires killall Dock after setting change
#      com.apple.finder AppleShowAllFiles -bool true
#      # 21 All file extenstions are displayed in Finder
#      # TODO: Requires killall Dock after setting change
#      NSGlobalDomain AppleShowAllExtensions -bool true
#      # 22 Display full POSIX path as Finder window title
#      # TODO: Requires killall Dock after setting change
#      com.apple.finder _FXShowPosixPathInTitle -bool true
#      # 23 Disable the warning when changing a file extension
#      # TODO: Requires killall Dock after setting change
#      com.apple.finder FXEnableExtensionChangeWarning -bool false
#      # 24 Avoid creating .DS_Store files on network volumes
#      # TODO: Requires killall Dock after setting change
#      com.apple.desktopservices DSDontWriteNetworkStores -bool true
#      # 25 Use list view in all Finder windows by default
#      # TODO: Requires killall Dock after setting change
#      # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`, `Nlsv`
#      # Icon view, (Three-) Column view, Flow view, (New-) List view
#      com.apple.finder FXPreferredViewStyle -string "clmv"
#      # 26 Empty Trash securely by default
#      # TODO: Requires killall Dock after setting change
#      com.apple.finder EmptyTrashSecurely -bool true
#      # 43 Documents are not stored to iCloud Drive by default. (May be mistaken if iCloud is disabled)
#      NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
#
#
#
#
#
#
#
#
#
