---

global_homebrew_packages:
  - dockutil
  - git
  - openssl
  # - python
  # - python3

global_homebrew_cask_apps:
  ### Standard applications
  - 1password
  # - dropbox
  # - evernote
  - firefox
  - google-chrome
  - little-snitch
  # - parallels
  - skype
  # - tableau
  - vyprvpn
  - expressvpn
  ### QuickLook plugins
  - qlstephen
  - quicklook-csv
  - qlmarkdown
  ### Security tools from https://objective-see.com/index.html
  # - dylibhijackscanner # not found in brew cask search
  - kextviewr
  - knockknock
  ## - lockdown # not working on Sierra 10.12
  ## - ostiarius # not needed after El Capitan 10.11
  - oversight
  - ransomwhere
  - taskexplorer
  - whatsyoursign
  # BlockBlock is at the end of the list so it doesn't stop the script
  - blockblock

global_google_fonts:
  - Audiowide
  - Dosis
  - "Open Sans"
  - Orbitron
  - Oswald

global_chrome_extensions:
  - { name: "1Password", id: "aomjjhallfgjeglblehebfpbcfeobpgk" }
  - { name: "Ghostery", id: "mlomiejdfkolichcflejclcbmpeaniij" }
  - { name: "GotoMeeting", id: "gaonpiemcjiihedemhopdoefaohcjoch" }
  - { name: "Session Buddy", id: "edacconmaakjimmfgnblocblbcdcpbko" }
  - { name: "uBlock Origin", id: "cjpalhdlnbpafiamejdnhcphjbkeiagm" }
  - { name: "Webex", id: "jlhmfgmfgeifomenelglieieghnjghma" }
  - { name: "TrafficLight", id: "cfnpidifppmenkapgihekkeednfoenal" }
  - { name: "Bear", id: "bipgnccfcjnfnpnnllchfeillaekkofo"}
